Turn optionalPeerDependencies into peerDependencies
T-Systems-MMS/aurelia-components pull request #48
Opened 2022-07-21 13:42 UTC by conradstrassburger

Fixes #47

2022-07-25 06:41 UTC, mreiche approved these changes

2022-08-10 12:16 UTC, Zsar requested changes

2022-08-10 12:16 UTC, Zsar commented on package.json
> +	"peerDependencies": {
The meta tag is missing though. `peerDependencies` will by default install everything therein for the client project, even if they have no desire to use one of them.

Please add `peerDependenciesMeta` as per discussion in the pertaining issue.

2022-08-12 10:35 UTC, Zsar commented on package.json
> +	"peerDependencies": {
@mreiche : FYI: @conradstrassburger went to vacation and handed this over to me yesterday.

I took the liberty to also move `peerDependencies` below `devDependencies` so the big-yet-mostly-irrelevant `peerDependenciesMeta` block can stay with the `peerDependencies` block it modifies without splitting the continous list of <whatever-kind-of>-dependencies.

2022-08-12 10:35 UTC, Zsar approved these changes

2022-08-29 12:50 UTC, mreiche approved these changes

2022-08-30 10:57 UTC, merged